{% set version_major = "8" %}
{% set version_minor = "0" %}
{% set version_hotfix = "0" %}

package:
  name: esa-snap
  version: "{{version_major}}.{{version_minor}}.{{version_hotfix}}"
  
source:
  fn:  esa-snap_sentinel_unix_{{version_major}}_{{version_minor}}.sh
  url: https://download.esa.int/step/snap/{{version_major}}.{{version_minor}}/installers/esa-snap_sentinel_unix_{{version_major}}_{{version_minor}}.sh
  md5: dcc44c6e305c6f299d4955a699461243

build:
  number: 0
  skip: true  # [win or osx]

requirements:
  host:
    - python
    - pyrosar
    - freetype
    - fontconfig
    - open-fonts
    
  run:
    - python
    - pyrosar
    - freetype
    - fontconfig
    - open-fonts

test:
  commands:
    - test -f $PREFIX/snap/bin/snap

about:
  home: https://step.esa.int
  license: Apache License 2.0
  summary: ESA Sentinel Application Platform (SNAP)

extra:
  recipe-maintainers:
    - ryan-salo