package:
  name: esa-snap
  version: 8.0.0
  
source:
  fn:  esa-snap_sentinel_unix_8_0.sh
  url: https://download.esa.int/step/snap/8.0/installers/esa-snap_sentinel_unix_8_0.sh
  md5: dcc44c6e305c6f299d4955a699461243

build:
  number: 0
  skip: true  # [win or osx]

requirements:
  host:
    - python
    - pyrosar
    
  run:
    - python
    - pyrosar
  
test:
  commands:
    - test -f $PREFIX/snap/bin/snap

about:
  home: https://step.esa.int
  license: Apache License 2.0
  summary: ESA Sentinel Application Platform (SNAP)

extra:
  recipe-maintainers:
    - ryan-salo